--- #YAML:1.0
name:               SOAP-UMRA
version:            1.0
abstract:           Access an UMRA SOAP service from perl
author:
    - Dennis Kaarsemaker <dennis@kaarsemaker.net>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    HTTP::Cookies:  0
    SOAP::Lite:     0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
